updating Readme.md with uninstall when pip package were already deployed on the same environment
openimis/openimis-be_py pull request #104
Opened 2022-05-25 16:37 UTC by mngoe

Changes proposed :

- When an environment is already deployed (first you deployed a main , then you deploy a dev environment) package already existing stay at the same version. 
Pip seems to compare only egg version and not branch (https://stackoverflow.com/questions/55615810/pip-install-from-repo-with-proper-caching-and-versioning).
Same problem on Windows and MacOsX

- Numpy and Pandas was not present in the requirements.txt , needed for the deployment (espcially on MacOS not tested on other environment).

2022-05-25 18:51 UTC, dragos-dobre requested changes

2022-05-25 18:51 UTC, dragos-dobre commented on README.md
> +  * if you previously installed OpenIMIS on another version, it seems safe to uninstall all previous modules-requirement to be sure it match current version `pip uninstall -r modules-requirements.txt
Please change OpenIMIS to openIMIS.

2022-05-30 07:41 UTC, delcroip commented on requirements.txt
> -pandas==1.0.1
of course, each module has requirements

2022-06-01 09:24 UTC, dborowiecki commented on requirements.txt
> -pandas==1.0.1
From perspective of Claim-AI those lines can be safely removed from requirements. 
Libraries required by module are already included in setup.py ([link](https://github.com/openimis/openimis-be-claim_ai_py/blob/da8fe1fbd2ee3f6b38b202893a0eaa04a1940745/setup.py#L30)), and should be installed automatically with the module.

2022-06-01 10:10 UTC, dragos-dobre approved these changes

2022-06-01 10:10 UTC, merged