ISE-183 OpenIMIS Sonar - Backend Module
openimis/openimis-be_py pull request #156
Opened 2023-06-21 09:49 UTC by kpavlenkoSoldevelo

fix for .flake8 configuration

2023-06-21 09:53 UTC, dborowiecki requested changes
The CI is failing. It seems like nose test executor is treating test_helpers as tests and tries to execute them. Please alternate django-nose configuration in order to skip helpers.

2023-06-28 07:08 UTC, pgesek commented on openIMIS/openIMIS/settings.py
> +    "drf_spectacular",  # Swagger UI for FHIR API
Remove this

2023-06-28 07:08 UTC, pgesek commented on openIMIS/openIMIS/settings.py
> +    "drf_spectacular",  # Swagger UI for FHIR API
The comma I mean

2023-06-28 13:32 UTC, dborowiecki approved these changes
LGTM

2023-06-28 13:32 UTC, dborowiecki approved these changes

2023-06-29 07:04 UTC, merged