OP-1529 Added reusable module CI
openimis/openimis-be_py pull request #172
Opened 2023-08-29 08:25 UTC by malinowskikam

[https://openimis.atlassian.net/browse/OP-1529](https://openimis.atlassian.net/browse/OP-1529)

2023-08-30 08:17 UTC, dborowiecki requested changes
Looks good, I left few comments with possible improvements.

2023-08-30 11:35 UTC, delcroip commented on .github/workflows/ci_module.yml
> +          ls -l
it can be useful when there is error on depedencies

2023-08-30 11:37 UTC, delcroip commented on .github/workflows/ci_module.yml
> +          if [ ${GITHUB_REF##*/} = "develop" ]; then export DBBRANCH="main"; else export DBBRANCH="develop"; fi
this is for the database: use develop unless the script is used when merging to main (in release) then it should use the main database (to ensure the release DB is correct)

2023-09-08 08:04 UTC, malinowskikam commented on .github/workflows/ci_module.yml
> +        if: success() || failure()
I tried this and it doesn't seem to work. For now we should keep this solution and think about enchancements

2023-09-08 12:26 UTC, dborowiecki approved these changes

2023-09-08 12:27 UTC, merged