add admin  auth for FS
openimis/openimis-be_py pull request #75
Opened 2021-12-15 10:22 UTC by delcroip

2021-12-15 10:25 UTC, dragos-dobre requested changes

2021-12-15 10:25 UTC, dragos-dobre commented on openimis.json
> +      "pip": "openimis-be-contribution-plan==1.3.2"
Is the version right here?

2021-12-16 09:23 UTC, dragos-dobre commented
We need to fix the system role id before updating main here.

2022-01-11 09:56 UTC, edarchis approved these changes

2022-02-08 09:02 UTC, merged